spring:
  profiles:
    active: dev

  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/pa-incoming-control-db

  jpa:
    database: POSTGRESQL
    show-sql: true

  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  
  security:
    oauth2:
      client:
        accessTokenUri: http://localhost:8081/oauth/check_token
        tokenName: token
        authenticationScheme: query
        clientAuthenticationScheme: form
        registered-redirect-uri: http://localhost:8082/
        pre-established-redirect-uri: http://localhost:8082/
      resource:
        userInfoUri: http://localhost:8081/user/info

server:
  servlet:
    session:
      cookie:
        secure: false
        http-only: false
  port: 8082
