spring:
  profiles:
    active: dev

  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/pa-incoming-control-db

  jpa:
    database: POSTGRESQL
    show-sql: true

  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  servlet:
    session:
      cookie:
        secure: false
        http-only: false
  port: 8082

security:
    oauth2:
      client:
        clientId: 1990922091019159
        clientSecret: 84a6b816305c2658f45ced45db6ab8ab 
        userAuthorizationUri: http://localhost:8081/oauth/check_token
        accessTokenUri: http://localhost:8081/oauth/check_token
        registered-redirect-uri: http://localhost:8082/
        pre-established-redirect-uri: http://localhost:8082/
      resource:
        userInfoUri: http://localhost:8081/user/info
